# Enable stateless CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
            token_id: submit

    csrf_protection:
        stateless_token_ids:
            - submit
            - authenticate
            - logout

#Mon csrf.yaml active la protection CSRF sur tous mes formulaires automatiquement. 
#Il protège spécifiquement 3 actions — la soumission des formulaires, la connexion et la déconnexion. 
#Le mode stateless permet de protéger la connexion même avant qu'une session soit ouverte.
