# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
            #Mon framework.yaml configure deux choses essentielles — 
            #la clé secrète de l'application utilisée pour sécuriser les tokens CSRF et les cookies,
            # et le système de sessions qui me permet de stocker le panier et gérer les utilisateurs connectés.
