framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
#Messenger gère les tâches en arrière-plan dans mon projet — principalement l'envoi d'emails après une commande.
# Si l'envoi échoue il réessaie automatiquement 3 fois avant de mettre la tâche en erreur
#C'est utilisé principalement pour l'envoi d'emails — quand un client passe une commande, l'email de confirmation est envoyé en arrière-plan sans faire attendre le client.