#Mon notifier.yaml envoie des notifications par email sur mon adresse personnelle pour tous les niveaux d'urgence — de la simple information jusqu'aux erreurs critiques
framework:
    notifier:
        chatter_transports:
        texter_transports:
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: kanem1468@gmail.com }
