framework:
    validation:
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
#C'est le système de validation de Symfony — il vérifie que les données saisies dans les formulaires sont correctes avant de les enregistrer en BDD
#c'est off en mode test pour pas ralentir les tests