<?php

namespace App\Security;

use Symfony\Component\HttpFoundation\RedirectResponse;// pour rediriger l'utilisateur après une connexion réussie vers la page d'accueil ou la page qu'il voulait visiter avant de se connecter.
use Symfony\Component\HttpFoundation\Request;// pour accéder aux données de la requête HTTP, comme les informations d'identification de l'utilisateur (email et mot de passe) et les données de session.
use Symfony\Component\HttpFoundation\Response;// pour retourner une réponse HTTP après le processus d'authentification, comme une redirection vers une page spécifique ou un message d'erreur en cas d'échec de l'authentification.
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;// pour générer des URL basées sur les routes définies dans l'application, ce qui est utile pour rediriger l'utilisateur vers la page d'accueil ou la page de connexion après une tentative d'authentification.       
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;// pour représenter le token d'authentification de l'utilisateur après une connexion réussie. Ce token contient les informations d'identification de l'utilisateur et est utilisé par le système de sécurité de Symfony pour gérer les autorisations et les accès aux ressources protégées.
use Symfony\Component\Security\Http\Authenticator\AbstractLoginFormAuthenticator;//c'est la classe qui nous permet de personnaliser notre propre système d'authentification via un formulaire de connexion en héritant de cette classe et en implémentant les méthodes nécessaires pour gérer le processus d'authentification, comme la validation des informations d'identification de l'utilisateur, la gestion des erreurs d'authentification et la redirection après une connexion réussie.
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\CsrfTokenBadge;//pour ajouter une vérification de token CSRF lors de l'authentification, ce qui permet de protéger le formulaire de connexion contre les attaques CSRF (Cross-Site Request Forgery). En utilisant CsrfTokenBadge, on peut s'assurer que le token CSRF envoyé avec la requête correspond à celui attendu par le système de sécurité, renforçant ainsi la sécurité de l'authentification.
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\RememberMeBadge;// pour ajouter la fonctionnalité "Remember Me" lors de l'authentification, ce qui permet à l'utilisateur de rester connecté même après la fermeture de son navigateur. En utilisant RememberMeBadge, on peut activer cette fonctionnalité dans le processus d'authentification, offrant ainsi une meilleure expérience utilisateur en évitant à l'utilisateur de devoir se reconnecter à chaque fois qu'il visite le site.
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge;// pour représenter l'utilisateur qui tente de se connecter lors du processus d'authentification. UserBadge est utilisé pour identifier l'utilisateur en fonction de son nom d'utilisateur (dans ce cas, l'email) et pour récupérer les informations de l'utilisateur à partir de la base de données ou d'une autre source de données. En utilisant UserBadge, on peut facilement intégrer la logique de récupération de l'utilisateur dans le processus d'authentification, ce qui facilite la validation des informations d'identification et la gestion des autorisations.
use Symfony\Component\Security\Http\Authenticator\Passport\Credentials\PasswordCredentials;// pour représenter les informations d'identification de l'utilisateur, en particulier le mot de passe, lors du processus d'authentification. PasswordCredentials est utilisé pour encapsuler le mot de passe saisi par l'utilisateur et le comparer avec le mot de passe stocké dans la base de données ou une autre source de données. En utilisant PasswordCredentials, on peut facilement intégrer la logique de validation du mot de passe dans le processus d'authentification, ce qui permet de vérifier si les informations d'identification fournies par l'utilisateur sont correctes et d'autoriser ou refuser l'accès en conséquence.
use Symfony\Component\Security\Http\Authenticator\Passport\Passport;// pour représenter l'ensemble des informations d'authentification de l'utilisateur lors du processus d'authentification. Passport est utilisé pour regrouper les badges (comme UserBadge, CsrfTokenBadge, RememberMeBadge) et les credentials (comme PasswordCredentials) en une seule entité qui peut être utilisée par le système de sécurité de Symfony pour gérer le processus d'authentification de manière cohérente et efficace. En utilisant Passport, on peut facilement organiser et gérer les différentes étapes du processus d'authentification, ce qui facilite la personnalisation et l'extension du système d'authentification selon les besoins de l'application.
use Symfony\Component\Security\Http\SecurityRequestAttributes;// pour accéder aux attributs de la requête liés à la sécurité, comme le dernier nom d'utilisateur saisi lors d'une tentative de connexion. En utilisant SecurityRequestAttributes, on peut stocker et récupérer ces informations dans la session de l'utilisateur, ce qui permet de fournir un retour d'information sur les erreurs de connexion et de pré-remplir le champ du nom d'utilisateur dans le formulaire de connexion pour une meilleure expérience utilisateur.
use Symfony\Component\Security\Http\Util\TargetPathTrait;// pour gérer la redirection de l'utilisateur vers la page qu'il voulait visiter avant de se connecter. TargetPathTrait fournit des méthodes pour stocker et récupérer l'URL cible dans la session de l'utilisateur, ce qui permet de rediriger l'utilisateur vers cette URL après une connexion réussie, offrant ainsi une expérience utilisateur fluide et cohérente.

class AppAuthenticator extends AbstractLoginFormAuthenticator  //pour dire que appauth... herite de la classe AbstractLoginFormAuthenticator qui est une classe de base fournie par Symfony pour créer un système d'authentification personnalisé basé sur un formulaire de connexion. En héritant de cette classe, on peut implémenter les méthodes nécessaires pour gérer le processus d'authentification, comme la validation des informations d'identification de l'utilisateur, la gestion des erreurs d'authentification et la redirection après une connexion réussie, tout en bénéficiant des fonctionnalités et de la structure fournies par Symfony pour faciliter le développement du système d'authentification.
{
    use TargetPathTrait;// pour inclure les méthodes fournies par TargetPathTrait dans la classe AppAuthenticator, ce qui permet de gérer facilement la redirection de l'utilisateur vers la page qu'il voulait visiter avant de se connecter. En utilisant ce trait, on peut stocker et récupérer l'URL cible dans la session de l'utilisateur, ce qui facilite la personnalisation du processus de redirection après une connexion réussie.

    public const LOGIN_ROUTE = 'app_login';// pour définir une constante LOGIN_ROUTE qui contient le nom de la route de connexion (app_login). Cette constante est utilisée dans la méthode getLoginUrl() pour générer l'URL de la page de connexion, ce qui permet de centraliser la définition de cette route et de faciliter les modifications futures si nécessaire.

    public function __construct(private UrlGeneratorInterface $urlGenerator)//pour genérer des url de redirection dans des routes definies dans le projet , comme la page d'accueil ou la page de connexion après une tentative d'authentification. En injectant UrlGeneratorInterface dans le constructeur, on peut facilement utiliser ce service pour générer des URL basées sur les routes définies dans l'application, ce qui facilite la personnalisation du processus de redirection après une connexion réussie.
    {
    }

    public function authenticate(Request $request): Passport// pour avoir accès aux données de la requête HTTP, comme les informations d'identification de l'utilisateur (email et mot de passe) et les données de session, lors du processus d'authentification. En utilisant Request comme argument de la méthode authenticate(), on peut récupérer ces informations pour valider les informations d'identification de l'utilisateur et gérer le processus d'authentification de manière efficace.
    {
        $email = $request->getPayload()->getString('email');// pour récupérer l'email saisi par l'utilisateur dans le formulaire de connexion. En utilisant $request->getPayload()->getString('email'), on accède aux données de la requête et on récupère la valeur du champ 'email' en tant que chaîne de caractères, ce qui permet de valider les informations d'identification de l'utilisateur lors du processus d'authentification.
//pourque l'email saisi par l'utilisateur soit stocké dans la session et puisse être pré-rempli dans le formulaire de connexion en cas d'erreur d'authentification, offrant ainsi une meilleure expérience utilisateur. En utilisant
        $request->getSession()->set(SecurityRequestAttributes::LAST_USERNAME, $email);// pour stocker le dernier nom d'utilisateur saisi par l'utilisateur dans la session. En utilisant $request->getSession()->set(SecurityRequestAttributes::LAST_USERNAME, $email), on enregistre l'email saisi par l'utilisateur dans la session sous la clé LAST_USERNAME, ce qui permet de pré-remplir le champ du nom d'utilisateur dans le formulaire de connexion en cas d'erreur d'authentification, offrant ainsi une meilleure expérience utilisateur.

        return new Passport(// pour créer et retourner une instance de Passport qui regroupe les informations d'authentification de l'utilisateur, comme le UserBadge pour identifier l'utilisateur, le PasswordCredentials pour valider le mot de passe, et les badges supplémentaires comme CsrfTokenBadge et RememberMeBadge pour gérer la sécurité et la fonctionnalité "Remember Me". En utilisant Passport, on peut organiser et gérer efficacement le processus d'authentification en intégrant toutes les étapes nécessaires pour valider les informations d'identification de l'utilisateur et gérer les aspects de sécurité liés à l'authentification.
            new UserBadge($email),// pour identifier l'utilisateur en fonction de son email lors du processus d'authentification. En utilisant UserBadge($email), on indique au système de sécurité de Symfony de rechercher l'utilisateur correspondant à cet email dans la base de données ou une autre source de données, ce qui permet de valider les informations d'identification de l'utilisateur et de gérer les autorisations en conséquence.
            new PasswordCredentials($request->getPayload()->getString('password')),// pour valider le mot de passe saisi par l'utilisateur lors du processus d'authentification. En utilisant PasswordCredentials($request->getPayload()->getString('password')), on encapsule le mot de passe saisi par l'utilisateur dans une instance de PasswordCredentials, ce qui permet de comparer ce mot de passe avec le mot de passe stocké dans la base de données ou une autre source de données pour vérifier si les informations d'identification fournies par l'utilisateur sont correctes et autoriser ou refuser l'accès en conséquence.
            [
                new CsrfTokenBadge('authenticate', $request->getPayload()->getString('_csrf_token')),// pour ajouter une vérification de token CSRF lors de l'authentification, ce qui permet de protéger le formulaire de connexion contre les attaques CSRF (Cross-Site Request Forgery). En utilisant CsrfTokenBadge('authenticate', $request->getPayload()->getString('_csrf_token')), on indique au système de sécurité de Symfony de vérifier que le token CSRF envoyé avec la requête correspond à celui attendu pour l'action 'authenticate', renforçant ainsi la sécurité de l'authentification.
                new RememberMeBadge(),// pour ajouter la fonctionnalité "Remember Me" lors de l'authentification, ce qui permet à l'utilisateur de rester connecté même après la fermeture de son navigateur. En utilisant RememberMeBadge(), on indique au système de sécurité de Symfony d'activer cette fonctionnalité dans le processus d'authentification, offrant ainsi une meilleure expérience utilisateur en évitant à l'utilisateur de devoir se reconnecter à chaque fois qu'il visite le site.
            ]
        );
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        //on recupere le panier avant la regeneration de la sesssion 
        $panier = $request->getSession()->get('panier', []);

        if ($targetPath = $this->getTargetPath($request->getSession(), $firewallName)) {//pour verifier si l'user avait une page cible avant de se connecter. En utilisant $this->getTargetPath($request->getSession(), $firewallName), on récupère l'URL cible stockée dans la session pour le firewall actuel, ce qui permet de rediriger l'utilisateur vers cette URL après une connexion réussie, offrant ainsi une expérience utilisateur fluide et cohérente.

            //on restaure le panier dans  la nouvelle session
            $request->getSession()->set('panier', $panier);// on donne au panier de cette nouvelle session les données du panier de l'ancienne session pour que l'utilisateur puisse retrouver son panier après s'être connecté, même si la session a été régénérée pour des raisons de sécurité. En utilisant $request->getSession()->set('panier', $panier), on s'assure que les données du panier sont préservées et accessibles dans la nouvelle session, offrant ainsi une meilleure expérience utilisateur en permettant à l'utilisateur de continuer à faire ses achats sans perdre les articles ajoutés à son panier avant de se connecter.
            
            return new RedirectResponse($targetPath);// pour rediriger l'utilisateur vers la page qu'il voulait visiter avant de se connecter. En utilisant new RedirectResponse($targetPath), on crée une réponse de redirection vers l'URL cible récupérée précédemment, ce qui permet à l'utilisateur de continuer sa navigation de manière fluide après une connexion réussie.
        }
        //on restaure le panier apres redirection de l'user 
        $request->getSession()->set('panier', $panier);
            
        

        // Redirection vers la page d'accueil après une connexion réussie
        return new RedirectResponse($this->urlGenerator->generate('app_home'));
    }

    protected function getLoginUrl(Request $request): string// pour générer l'URL de la page de connexion. En utilisant $this->urlGenerator->generate(self::LOGIN_ROUTE), on génère l'URL basée sur la route définie par LOGIN_ROUTE (app_login), ce qui permet de centraliser la définition de cette route et de faciliter les modifications futures si nécessaire.
    {
        return $this->urlGenerator->generate(self::LOGIN_ROUTE);// pour générer l'URL de la page de connexion.
    }
}